/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frontend_jni_PSMoveManager */

#ifndef _Included_frontend_jni_PSMoveManager
#define _Included_frontend_jni_PSMoveManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frontend_jni_PSMoveManager
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frontend_jni_PSMoveManager_close0
  (JNIEnv *, jobject);

/*
 * Class:     frontend_jni_PSMoveManager
 * Method:    init0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_frontend_jni_PSMoveManager_init0
  (JNIEnv *, jobject);

/*
 * Class:     frontend_jni_PSMoveManager
 * Method:    getPoint0
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_frontend_jni_PSMoveManager_getPoint0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
