/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frontend_jni_JniHelper */

#ifndef _Included_frontend_jni_JniHelper
#define _Included_frontend_jni_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frontend_jni_JniHelper
 * Method:    recognize0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_frontend_jni_JniHelper_recognize0
  (JNIEnv *, jobject);

/*
 * Class:     frontend_jni_JniHelper
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frontend_jni_JniHelper_close0
  (JNIEnv *, jobject);

/*
 * Class:     frontend_jni_JniHelper
 * Method:    init0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_frontend_jni_JniHelper_init0
  (JNIEnv *, jobject);

/*
 * Class:     frontend_jni_JniHelper
 * Method:    getPoint0
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_frontend_jni_JniHelper_getPoint0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
